# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/imaging.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61pi/imaging.proto\x12\x07imaging\" \n\x10GrayScaleRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x11GrayScaleResponse\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\x32O\n\x07Imaging\x12\x44\n\tGrayScale\x12\x19.imaging.GrayScaleRequest\x1a\x1a.imaging.GrayScaleResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.imaging_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GRAYSCALEREQUEST']._serialized_start=30
  _globals['_GRAYSCALEREQUEST']._serialized_end=62
  _globals['_GRAYSCALERESPONSE']._serialized_start=64
  _globals['_GRAYSCALERESPONSE']._serialized_end=99
  _globals['_IMAGING']._serialized_start=101
  _globals['_IMAGING']._serialized_end=180
# @@protoc_insertion_point(module_scope)
