# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api import imaging_pb2 as api_dot_imaging__pb2


class ImagingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GrayScale = channel.unary_unary(
                '/imaging.Imaging/GrayScale',
                request_serializer=api_dot_imaging__pb2.GrayScaleRequest.SerializeToString,
                response_deserializer=api_dot_imaging__pb2.GrayScaleResponse.FromString,
                )


class ImagingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GrayScale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImagingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GrayScale': grpc.unary_unary_rpc_method_handler(
                    servicer.GrayScale,
                    request_deserializer=api_dot_imaging__pb2.GrayScaleRequest.FromString,
                    response_serializer=api_dot_imaging__pb2.GrayScaleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imaging.Imaging', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Imaging(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GrayScale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/imaging.Imaging/GrayScale',
            api_dot_imaging__pb2.GrayScaleRequest.SerializeToString,
            api_dot_imaging__pb2.GrayScaleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
